import "@/styles/globals.css";
import type { Metadata } from "next";
import QueryClientConfig from "@/configs/QueryClientConfig";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<QueryClientConfig>
			<html lang="en">
				<head>
					<meta name="author" content="Migranium" />
					<meta name="theme-color" content="#ffffff" />
					<meta
						name="viewport"
						content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
					/>

					<link
						rel="apple-touch-icon"
						sizes="180x180"
						href="/assets/apple-touch-icon.png"
					/>
					<link
						rel="icon"
						type="image/png"
						sizes="32x32"
						href="/assets/favicon-32x32.png"
					/>
					<link
						rel="icon"
						type="image/png"
						sizes="16x16"
						href="/assets/favicon-16x16.png"
					/>

					<link rel="canonical" href="https://www.migranium.com/" />
					<link
						rel="preload"
						href="../styles/globals.css"
						as="style"
					/>

					<title>
						Migranium: Workflow Automation, Operations Analytics,
						Queue Management and Scheduling App
					</title>
					<meta name="language" content="English" />
					<meta
						name="title"
						content="Migranium: Workflow Automation, Operations Analytics, Queue Management and Scheduling App"
					/>
					<meta
						name="description"
						content="Transform your clinic's efficiency with Migranium. Designed for busy healthcare providers, our app simplifies patient flow with intelligent queue management. Experience effortless scheduling, and unlock the potential of operations analytics to optimize your practice. With Migranium, reduce wait times, increase patient satisfaction, and take control of your day-to-day clinic management. Join the forefront of healthcare service innovation with Migranium—where care meets efficiency."
					/>
					<meta
						name="keywords"
						content="wait time management, virtual queue optimization, queue management software, online appointment scheduling, queue management system, digital queue management, real-time waitlist updates, queue analytics solutions, reduce customer wait times, efficient queue scheduling, streamline customer flow, queue management app, appointment booking software, online check-in solutions, queue forecasting tools, improve customer experience, resource allocation optimization, time slot management system, queue segmentation strategies, enhance service efficiency, virtual queue, queue management, scheduling, online appointment, waitlist, customer flow, digital queue, queue optimization, real-time notifications, self-service booking, service prioritization, resource allocation, capacity management, queue analytics, mobile app integration, online check-in, queue segmentation, time slot management, queue forecasting, customer experience enhancement, migranium, queue, schedule, operation, customer service, virtual queue, track queue, track appointment, wait time"
					/>
					<meta name="robots" content="index, follow" />
					<meta
						httpEquiv="Content-Type"
						content="text/html; charset=utf-8"
					/>

					{/* Open Graph Meta Taga */}
					<meta property="og:type" content="website" />
					<meta
						property="og:url"
						content="https://www.migranium.com/"
					/>
					<meta
						property="og:title"
						content="Migranium: Workflow Automation, Operations Analytics, Queue Management and Scheduling App"
					/>
					<meta
						property="og:description"
						content="Transform your clinic's efficiency with Migranium. Designed for busy healthcare providers, our app simplifies patient flow with intelligent queue management."
					/>
					<meta
						property="og:image"
						content="https://www.migranium.com/assets/og-image.png"
					/>

					{/* Twitter Meta Taga */}
					<meta name="twitter:card" content="summary_large_image" />
					<meta
						name="twitter:url"
						content="https://www.migranium.com/"
					/>
					<meta
						name="twitter:title"
						content="Migranium: Workflow Automation, Operations Analytics, Queue Management and Scheduling App"
					/>
					<meta
						name="twitter:description"
						content="Transform your clinic's efficiency with Migranium. Designed for busy healthcare providers, our app simplifies patient flow with intelligent queue management."
					/>
					<meta
						name="twitter:image"
						content="https://www.migranium.com/assets/og-image.png"
					/>
				</head>
				<body>{children}</body>
				<script
					type="application/ld+json"
					dangerouslySetInnerHTML={{
						__html: `
								{
									"@context": "https://schema.org",
									"@type": "Organization",
									"url": "https://www.migranium.com/",
									"name": "Migranium",
									"logo": "https://www.migranium.com/assets/logo.png",
									"sameAs": [
										"https://www.facebook.com/migranium",
										"https://twitter.com/migranium",
										"https://www.linkedin.com/company/migranium"
									]
								}
            `,
					}}
				/>
			</html>
		</QueryClientConfig>
	);
}
