import "@/styles/globals.css";
import type { Metadata } from "next";
import QueryClientConfig from "@/configs/QueryClientConfig";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<QueryClientConfig>
			<html lang="en">
				<body>{children}</body>
			</html>
		</QueryClientConfig>
	);
}
